# Generated by Django 4.2 on 2023-04-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_journal_final", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thought",
            name="content",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="thought",
            name="poster",
            field=models.ForeignKey(
                max_length=10,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poster",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
