# Generated by Django 4.2 on 2023-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_journal_final", "0002_alter_thought_content_alter_thought_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thought",
            name="content",
            field=models.TextField(max_length=5000),
        ),
    ]
